listen: 8080
strategy: least_conn
sticky_session: true

upstream:
  serviceA:
    - url: "http://serviceA-backend1.example.com"
      weight: 3
      max_fails: 3
      fail_timeout: 30
    - url: "http://serviceA-backend2.example.com"
      weight: 2
      max_fails: 3
      fail_timeout: 30

  serviceB:
    - url: "http://serviceB-backend1.example.com"
      weight: 2
      max_fails: 3
      fail_timeout: 30
    - url: "http://serviceB-backend2.example.com"
      weight: 1
      max_fails: 3
      fail_timeout: 30

path_routes:
  - path: "/serviceA/"
    proxy_pass: serviceA

  - path: "/serviceB/"
    proxy_pass: serviceB

ssl:
  enabled: true
  certificate: "/etc/nginx/ssl/cert.pem"
  certificate_key: "/etc/nginx/ssl/key.pem"

health_check:
  endpoint: "/healthcheck"
  interval: 5

rate_limit:
  enabled: true
  zone: "api"
  rate: "10r/s"
  burst: 5

timeouts:
  connect: 10
  send: 30
  read: 30