listen: 8080
strategy: least_conn
sticky_session: true

upstream:
  localhostA:
    - url: "https://httpbin.org/"
      weight: 3
      max_fails: 3
      fail_timeout: 30
    - url: "https://httpbin.org/"
      weight: 2
      max_fails: 3
      fail_timeout: 30

  localhostB:
    - url: "https://httpbin.org/"
      weight: 2
      max_fails: 3
      fail_timeout: 30
    - url: "https://httpbin.org/"
      weight: 1
      max_fails: 3
      fail_timeout: 30

path_routes:
  - path: "/serviceA/"
    proxyPass: http://google.com

  - path: "/serviceB/"
    proxyPass: http://localhostA

ssl:
  enabled: true
  certificate: "/etc/nginx/ssl/cert.pem"
  certificate_key: "/etc/nginx/ssl/key.pem"

health_check:
  endpoint: "/healthcheck"
  interval: 5

rate_limit:
  enabled: true
  zone: "api"
  rate: "10r/s"
  burst: 5

timeouts:
  connect: 10
  send: 30
  read: 30